# Sheduling, see: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#example-nightly-build-with-different-frequencies
# Disable other triggers
pr: none
trigger: none

# Set schedule
schedules:
- cron: "0 3 * * 1-5"
  displayName: M-F 3:00 AM (UTC) daily build
  branches:
    include:
    - master

pool:
  vmImage: 'ubuntu-latest'
variables:
  buildConfiguration: 'Release'

steps:
# Prepare SonarCloud
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'fredrikmjohansson'
    scannerMode: 'MSBuild'
    projectKey: 'FredrikJ365_JustSomeService'
    projectName: 'JustSomeService'

# Build it
- script: dotnet build src/src.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# Test it and collect coverage
- task: DotNetCoreCLI@2
  inputs:
    command: test
    projects: '**/*test/srcTest/*.csproj'
    arguments: -c $(BuildConfiguration) --collect:"Code Coverage" -- RunConfiguration.DisableAppDomain=true
  displayName: Run Tests

# Run SonarCloud
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'