# Sheduling, see: https://docs.microsoft.com/en-us/azure/devops/pipelines/process/scheduled-triggers?view=azure-devops&tabs=yaml#example-nightly-build-with-different-frequencies

# Disable other triggers
pr: none
trigger: none

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

# Prepare SonarCloud
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'SonarCloud'
    organization: 'fredrikmjohansson'
    scannerMode: 'MSBuild'
    projectKey: 'FredrikJ365_JustSomeService'
    projectName: 'JustSomeService'

# Build it
- script: dotnet build src/src.csproj --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'

# Run SonarCloud
- task: SonarCloudAnalyze@1
- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'